version: '3'

networks:
  project:

services:
  nginx:
    build:
      context: images/nginx/1.22
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        TZ: ${WORKSPACE_TIMEZONE}
    container_name: nginx
    working_dir: /home/${USER_NAME}/projects
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./projects:/home/${USER_NAME}/projects
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    networks:
      project:
        # Можно добавить домены проектов, чтобы можно было на них стучать из php контейнера
        aliases:
          - akb-priem.localhost
          - lazardent.localhost

  php-8.0:
    build:
      context: images/php/8.0
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /home/${USER_NAME}/projects
    container_name: php-8.0
    volumes:
      - ./projects:/home/${USER_NAME}/projects
    ports:
      - "${PHP_8_0_PORT}:9000"
      - "25:25"
    networks:
      - project

  php-7.3:
    build:
      context: images/php/7.3
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /home/${USER_NAME}/projects
    container_name: php-7.3
    volumes:
      - ./projects:/home/${USER_NAME}/projects
    ports:
      - "${PHP_7_3_PORT}:9000"
    networks:
      - project

  mysql-8:
    build:
      context: images/mysql/8.0
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        TZ: ${WORKSPACE_TIMEZONE}
    container_name: mysql-8
    volumes:
      - ./mysql/8.0/conf.d:/etc/mysql/conf.d
      - ./mysql/8.0/logs:/var/log/mysql/
      - ./mysql/8.0/dump:/dump
    ports:
      - "${MYSQL_8_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_8_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_8_TCP_PORT}
    networks:
      - project

  mariadb-10.3: 
    build:
      context: images/mariadb/10.3
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        TZ: ${WORKSPACE_TIMEZONE}
    container_name: mariadb-10.3
    volumes:
      - ./mariadb/10.3/dump:/dump
    ports:
      - "${MARIADB_13_0_PORT}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_13_0_ROOT_PASSWORD}
    networks:
      - project

  node-18:
    build:
      context: images/node/18
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /home/${USER_NAME}/projects
    stdin_open: true
    tty: true
    container_name: node-18
    volumes:
      - ./projects:/home/${USER_NAME}/projects
    ports:
      - "${NODE_18_PORT}:8080"
    networks:
      - project
